name: Build and Deploy to Heroku

on:
  push:
    branches:
      - main  # Trigger this workflow when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specify your Node.js version

    - name: Install dependencies
      run: |
        npm install
        cd backend
        npm install  # If you have a separate backend folder

    - name: Build React app
      run: |
        cd frontend  # Change this if your frontend is in a different folder
        npm run build

    - name: Deploy to Heroku
      uses: akshnz/heroku-deploy@v1.1.6
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: 'your-email@example.com'  # Replace with your Heroku email
